# ??Spring????????????????????????????
spring:
  application:
    name: eureka-server

  security:
    user:
      name: root
      password: root

# eureka
server:
  port: 8060

eureka:
  instance:
    preferIpAddress: true
    hostname: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
#      prefer-ip-address: true
  client:
    #是否将自己注册到注册中心
    register-with-eureka: true
    #是否从eureka中获取注册信息
    fetch-registry: true
    #配置暴露给eureka client的请求地址
    service-url:
      defaultZone: http://localhost:8070/eureka/,http://localhost:8080/eureka/
#       defaultZone: http://localhost:${server.port}/eureka/



