# ??Spring????????????????????????????
spring:
  application:
    name: eureka-server

  security:
    user:
      name: root
      password: root

# eureka
server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
    hostname: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
    # 服务失效时间，失效的服务将被剔除。单位：秒，默认90
    lease-expiration-duration-in-seconds: 30
  server:
    #清理无效节点，默认60毫秒
    eviction-interval-timer-in-ms: 30000
  #    prefer-ip-address: true
  client:
    #是否将自己注册到注册中心
    register-with-eureka: false
#    设置为true，用于eureka集群配置
#    register-with-eureka: true
    #是否从eureka中获取注册信息
    fetch-registry: false
#    设置为true，用于eureka集群配置
#    fetch-registry: true
    #配置暴露给eureka client的请求地址
    service-url:
#      defaultZone: http://localhost:8070/eureka/,http://localhost:8060/eureka/
       defaultZone: http://localhost:${server.port}/eureka/


